In [1]:
import pandas as pd

# 1. Daftar file tahunan beserta tahunnya
files_yearly = {
    'Pemeliharaan Kendaraan 2023.csv': 2023,
    'Pemeliharaan Kendaraan 2024.csv': 2024,
    'Pemeliharaan Kendaraan 2025.csv': 2025
}

# Membaca dan menggabungkan file 2023-2025
df_yearly_list = []
for f, tahun in files_yearly.items():
    temp_df = pd.read_csv(f, sep=';')
    temp_df['Tahun'] = tahun   # <-- Menambahkan kolom tahun sesuai file
    temp_df['Sumber'] = f 
    df_yearly_list.append(temp_df)

df_yearly = pd.concat(df_yearly_list, ignore_index=True)

# 2. Membaca data.csv
df_data = pd.read_csv('data.csv', sep=';')

# 3. Membersihkan kolom NILAI di data.csv
df_data['NILAI'] = df_data['NILAI'].str.replace('Rp ', '', regex=False).str.replace('.', '', regex=False).astype(float)

# 4. Melakukan Rename kolom data.csv
mapping = {
    'NOPOL': 'Nopol',
    'REKANAN': 'Vendor',
    'NILAI': 'Total Biaya',
    'JENIS PEMELIHARAAN': 'Keterangan',
    'MERK': 'Type',
    'KETERANGAN': 'Status Proses',
    'TANGGAL': 'Tanggal_Full'
}
df_data_renamed = df_data.rename(columns=mapping)

# 5. Menyamakan kolom 'Bulan' & 'Tahun' (Ekstrak dari Tanggal_Full)
df_data_renamed['Tanggal_Full'] = pd.to_datetime(df_data_renamed['Tanggal_Full'], dayfirst=True)
month_map = {
    1: 'Januari', 2: 'Februari', 3: 'Maret', 4: 'April', 5: 'Mei', 6: 'Juni',
    7: 'Juli', 8: 'Agustus', 9: 'September', 10: 'Oktober', 11: 'November', 12: 'Desember'
}
df_data_renamed['Bulan'] = df_data_renamed['Tanggal_Full'].dt.month.map(month_map)
df_data_renamed['Tahun'] = df_data_renamed['Tanggal_Full'].dt.year # <-- Menambahkan kolom tahun otomatis
df_data_renamed['Sumber'] = 'data.csv'

# 6. Menggabungkan data tahunan dengan data.csv
df_final = pd.concat([df_yearly, df_data_renamed], ignore_index=True)

print("Proses penggabungan selesai! Kolom 'Tahun' telah ditambahkan.")

Proses penggabungan selesai! Kolom 'Tahun' telah ditambahkan.

In [2]:
df_final

,Bulan,Vendor,Jenis Kendaraan,Type,Nopol,Sparepart,Jasa,PPN,Total Biaya,Keterangan,Biaya Sebelum PPN,PPN Rate,Sparepart %,Jasa %,Tahun,Sumber,Tanggal_Full,OPD,Status Proses
0,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1929 BP,1712705.0,1121250,311728,3145683,Rusak Ringan,2833955.0,"0,11","0,544462045","0,356440875",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
1,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Sedan,Camry,L 1663 PP,2359574.0,2951324,584200,5895098,Rusak Sedang,5310898.0,"0,11","0,400260352","0,500640363",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
2,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Sedan,Camry,L 1164 BS,2586196.0,2785086,590842,5962124,Rusak Sedang,5371282.0,"0,11","0,433770918","0,467129835",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
3,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1903 FP,1865925.0,1234837,341086,3441848,Rusak Ringan,3100762.0,"0,11","0,542128821","0,358771509",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
4,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1516 QP,2147459.0,1112962,358648,3619069,Rusak Ringan,3260421.0,"0,11","0,593373323","0,307527157",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5482,Januari,PT. ASTRA INTERNATIONAL TBK (AUTO2000 BASUKI R...,NaN,NEW KIJANG INNOVA 2.4 Q A/T DIESEL VENTURER VI...,L 1362 DP,NaN,NaN,NaN,0.0,Perawatan Rusak Sedang,NaN,NaN,NaN,NaN,2026,data.csv,2026-01-17,"BAGIAN UMUM, PROTOKOL DAN KOMUNIKASI PIMPINAN",Konfirmasi Kendaraan Datang
5483,Januari,PT. ASTRA INTERNATIONAL TBK (AUTO2000 BASUKI R...,NaN,KIJANG INNOVA 2.0 G AT,L 1772 PP,NaN,NaN,NaN,0.0,Perawatan Berkala Tune UP,NaN,NaN,NaN,NaN,2026,data.csv,2026-01-17,"BAGIAN UMUM, PROTOKOL DAN KOMUNIKASI PIMPINAN",SPK Disetujui
5484,Januari,PT. ASTRA INTERNATIONAL TBK (ISUZU MARGOMULYO),NaN,TBR54 TURBO PICK UP,L 8836 CP,NaN,NaN,NaN,0.0,Perawatan Rusak Sedang,NaN,NaN,NaN,NaN,2026,data.csv,2026-01-19,KECAMATAN ASEMROWO,Konfirmasi Kendaraan Datang
5485,Januari,PT. ASTRA INTERNATIONAL TBK (ISUZU WARU),NaN,DAIHATSU F601RV,L 1954 BP,NaN,NaN,NaN,0.0,Perawatan Rusak Sedang,NaN,NaN,NaN,NaN,2026,data.csv,2026-01-20,DINAS KETAHANAN PANGAN DAN PERTANIAN,Konfirmasi Kendaraan Datang
5486,Januari,PT. ASTRA INTERNATIONAL TBK (ISUZU WARU),NaN,TBR54F TURBO LV,L 1350 CP,NaN,NaN,NaN,0.0,Perawatan Rusak Sedang,NaN,NaN,NaN,NaN,2026,data.csv,2026-01-26,BADAN PENDAPATAN DAERAH,SPK Disetujui

In [3]:
# 1. Pastikan kolom Total Biaya adalah tipe angka (numeric)
# Ini perlu dilakukan jika ada data yang masih terbaca sebagai teks dengan titik/koma
df_final['Total Biaya'] = pd.to_numeric(
    df_final['Total Biaya'].astype(str).str.replace('.', '', regex=False).str.replace(',', '.', regex=False), 
    errors='coerce'
).fillna(0)

# 2. Hapus baris yang Total Biayanya 0 atau 1
df_final = df_final[~df_final['Total Biaya'].isin([0, 1])]

# 3. (Opsional) Hapus juga jika ada nilai yang negatif atau di bawah 1
# df_final = df_final[df_final['Total Biaya'] > 1]

print(f"Pembersihan selesai! Sisa baris sekarang: {len(df_final)}")
df_final.head()

Pembersihan selesai! Sisa baris sekarang: 3351

,Bulan,Vendor,Jenis Kendaraan,Type,Nopol,Sparepart,Jasa,PPN,Total Biaya,Keterangan,Biaya Sebelum PPN,PPN Rate,Sparepart %,Jasa %,Tahun,Sumber,Tanggal_Full,OPD,Status Proses
0,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1929 BP,1712705.0,1121250,311728,3145683.0,Rusak Ringan,2833955.0,"0,11","0,544462045","0,356440875",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
1,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Sedan,Camry,L 1663 PP,2359574.0,2951324,584200,5895098.0,Rusak Sedang,5310898.0,"0,11","0,400260352","0,500640363",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
2,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Sedan,Camry,L 1164 BS,2586196.0,2785086,590842,5962124.0,Rusak Sedang,5371282.0,"0,11","0,433770918","0,467129835",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
3,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1903 FP,1865925.0,1234837,341086,3441848.0,Rusak Ringan,3100762.0,"0,11","0,542128821","0,358771509",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN
4,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Mini bus,IMV,L 1516 QP,2147459.0,1112962,358648,3619069.0,Rusak Ringan,3260421.0,"0,11","0,593373323","0,307527157",2023,Pemeliharaan Kendaraan 2023.csv,NaT,NaN,NaN

In [4]:
# 1. Membuat 'Kamus' Referensi dari Nopol ke Jenis Kendaraan & Type
# Kita ambil baris yang datanya lengkap, lalu hapus duplikat Nopol-nya
referensi_jenis = df_final.dropna(subset=['Jenis Kendaraan']).drop_duplicates('Nopol')[['Nopol', 'Jenis Kendaraan']]
referensi_type = df_final.dropna(subset=['Type']).drop_duplicates('Nopol')[['Nopol', 'Type']]

# 2. Mengisi (Fillna) kolom yang kosong berdasarkan Nopol
# Kita jadikan Nopol sebagai index sementara agar pengisian lebih cepat
df_final = df_final.set_index('Nopol')

df_final['Jenis Kendaraan'] = df_final['Jenis Kendaraan'].fillna(referensi_jenis.set_index('Nopol')['Jenis Kendaraan'])
df_final['Type'] = df_final['Type'].fillna(referensi_type.set_index('Nopol')['Type'])

# Kembalikan Nopol menjadi kolom biasa
df_final = df_final.reset_index()

# 3. Jalankan pembersihan yang diminta sebelumnya
# Hapus Total Biaya 0 atau 1
df_final['Total Biaya'] = pd.to_numeric(df_final['Total Biaya'], errors='coerce').fillna(0)
df_final = df_final[~df_final['Total Biaya'].isin([0, 1])]

# Hapus Keterangan yang kosong
df_final = df_final.dropna(subset=['Keterangan'])

print("Selesai! Jenis Kendaraan dan Type telah diisi berdasarkan referensi Nopol.")

Selesai! Jenis Kendaraan dan Type telah diisi berdasarkan referensi Nopol.

In [5]:
# 1. Menghapus baris di mana kolom 'Keterangan' kosong (NaN)
df_final = df_final.dropna(subset=['Keterangan'])

# 2. (Tambahan) Jika ada 'Keterangan' yang hanya berisi spasi kosong, bisa dibersihkan juga:
df_final = df_final[df_final['Keterangan'].astype(str).str.strip() != ""]

print(f"Pembersihan selesai! Sisa baris setelah menghapus Keterangan kosong: {len(df_final)}")
df_final.head()
df_final.info()

Pembersihan selesai! Sisa baris setelah menghapus Keterangan kosong: 3238
<class 'pandas.DataFrame'>
Index: 3238 entries, 0 to 3350
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nopol              3237 non-null   str
 1   Bulan              3238 non-null   str
 2   Vendor             3238 non-null   str
 3   Jenis Kendaraan    2002 non-null   str
 4   Type               3238 non-null   str
 5   Sparepart          798 non-null    object
 6   Jasa               799 non-null    object
 7   PPN                799 non-null    str
 8   Total Biaya        3238 non-null   float64
 9   Keterangan         3238 non-null   str
 10  Biaya Sebelum PPN  798 non-null    object
 11  PPN Rate           799 non-null    str
 12  Sparepart %        798 non-null    str
 13  Jasa %             799 non-null    str
 14  Tahun              3238 non-null   int64
 15  Sumber             3238 non-null   str
 16  Tanggal_Full       2439 non-null   datetime64[us]
 17  OPD                2439 non-null   str
 18  Status Proses      2439 non-null   str
dtypes: datetime64[us](1), float64(1), int64(1), object(3), str(13)
memory usage: 505.9+ KB

In [6]:
# Menghapus kolom yang memiliki nilai kosong (NaN) 
# Kita set thresh=3237 agar hanya kolom yang terisi penuh yang dipertahankan
df_final = df_final.dropna(axis=1, thresh=3237)

# Menampilkan info untuk memastikan kolom sudah terhapus
df_final.info()

<class 'pandas.DataFrame'>
Index: 3238 entries, 0 to 3350
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nopol        3237 non-null   str
 1   Bulan        3238 non-null   str
 2   Vendor       3238 non-null   str
 3   Type         3238 non-null   str
 4   Total Biaya  3238 non-null   float64
 5   Keterangan   3238 non-null   str
 6   Tahun        3238 non-null   int64
 7   Sumber       3238 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 227.7 KB

In [7]:
df_final

,Nopol,Bulan,Vendor,Type,Total Biaya,Keterangan,Tahun,Sumber
0,L 1929 BP,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,IMV,3145683.0,Rusak Ringan,2023,Pemeliharaan Kendaraan 2023.csv
1,L 1663 PP,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Camry,5895098.0,Rusak Sedang,2023,Pemeliharaan Kendaraan 2023.csv
2,L 1164 BS,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,Camry,5962124.0,Rusak Sedang,2023,Pemeliharaan Kendaraan 2023.csv
3,L 1903 FP,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,IMV,3441848.0,Rusak Ringan,2023,Pemeliharaan Kendaraan 2023.csv
4,L 1516 QP,Januari,PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI ...,IMV,3619069.0,Rusak Ringan,2023,Pemeliharaan Kendaraan 2023.csv
...,...,...,...,...,...,...,...,...
3346,L 0013 BP,Desember,CV. ASRI PUCANG (TOYOTA),KIJANG INNOVA 2.0 G AT,23160000.0,Perawatan Berkala Tune UP,2023,data.csv
3347,L 1907 BP,Maret,PT. ASTRA INTERNATIONAL TBK (ISUZU KOMBES M DU...,PANTHER LM FF VIN,90214000.0,Perawatan Rusak Berat,2024,data.csv
3348,L 9329 AP,Juli,PT SRIKANDI DIAMOND INDAH MOTORS,L300 FB-R 4X2 MT,21936200.0,Perawatan Berkala Tune UP,2024,data.csv
3349,L 1825 AP,September,PT. ASTRA INTERNATIONAL TBK (ISUZU KOMBES M DU...,K2700,74756100.0,Perawatan Rusak Sedang,2024,data.csv
3350,L 8441 CP,September,PT SRIKANDI DIAMOND INDAH MOTORS,L300 FB-R 4X2 MT,88726000.0,Perawatan Rusak Berat,2024,data.csv

In [8]:
# Menampilkan daftar unik tipe mobil
print(df_final['Type'].unique())
# Menampilkan jumlah total jenis tipe mobil
jumlah_tipe = df_final['Type'].nunique()
print(f"Total ada {jumlah_tipe} jenis tipe mobil.")
# Menampilkan tiap tipe mobil dan berapa kali muncul di data
print(df_final['Type'].value_counts())
# Menampilkan 10 tipe mobil terbanyak dalam bentuk tabel
df_tipe = df_final['Type'].value_counts().reset_index()
df_tipe.columns = ['Tipe Mobil', 'Jumlah']
df_tipe

<StringArray>
[                     'IMV',                    'Camry',
                    'Other',                   'Soluna',
                    'Hiace',                   'Kijang',
                    'TBR54',                'Nseries77',
                   'TBR541',               'Mitsubishi',
 ...
          'WU342R MICROBUS',     'KIJANG INNOVA V XW43',
               'NKR71TRUCK',           'ACCORD CP2 2.4',
    'COROLLA ALTIS 2.0 A/T',  'MITSIBISHI PAJERO S2 5D',
              'SOLUNA AL50',          'CAMRY 2.5 V A/T',
   'FORTUNER 2.4 G 4X2 A/T', 'FORTUNER 2.8 VRZ 4X2 A/T']
Length: 239, dtype: str
Total ada 239 jenis tipe mobil.
Type
TBR54 TURBO PICK UP         227
TBR54                       213
KIJANG INNOVA 2.0 G AT      184
IMV                         168
TBR541                      148
                           ...
COROLLA ALTIS 2.0 A/T         1
MITSIBISHI PAJERO S2 5D       1
SOLUNA AL50                   1
FORTUNER 2.4 G 4X2 A/T        1
FORTUNER 2.8 VRZ 4X2 A/T      1
Name: count, Length: 239, dtype: int64

                   Tipe Mobil  Jumlah
0         TBR54 TURBO PICK UP     227
1                       TBR54     213
2      KIJANG INNOVA 2.0 G AT     184
3                         IMV     168
4                      TBR541     148
..                        ...     ...
234     COROLLA ALTIS 2.0 A/T       1
235   MITSIBISHI PAJERO S2 5D       1
236               SOLUNA AL50       1
237    FORTUNER 2.4 G 4X2 A/T       1
238  FORTUNER 2.8 VRZ 4X2 A/T       1

[239 rows x 2 columns]

In [9]:
# Menyimpan hasil akhir ke file CSV
#df_final.to_csv('Data_Pemeliharaan_Bersih_Final.csv', index=False, sep=';')

#print("File berhasil disimpan dengan nama: Data_Pemeliharaan_Bersih_Final.csv")

In [10]:
#drop missing value
df_final = df_final.dropna()
df_final.info()

<class 'pandas.DataFrame'>
Index: 3237 entries, 0 to 3350
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nopol        3237 non-null   str
 1   Bulan        3237 non-null   str
 2   Vendor       3237 non-null   str
 3   Type         3237 non-null   str
 4   Total Biaya  3237 non-null   float64
 5   Keterangan   3237 non-null   str
 6   Tahun        3237 non-null   int64
 7   Sumber       3237 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 227.6 KB

In [ ]:
# Menampilkan daftar unik tipe mobil
print(df_final['Nopol'].unique())
# Menampilkan jumlah total jenis tipe mobil
jumlah_tipe = df_final['Nopol'].nunique()
#save to csv
df_final.to_csv('Data_Kendaraan_Bersih.csv', index=False, sep=';')

<StringArray>
['L 1929 BP', 'L 1663 PP', 'L 1164 BS', 'L 1903 FP', 'L 1516 QP', 'L 1711 FP',
 'L 1877 FP', 'L 1927 EP', 'L 1852 PP', 'L 1926 BP',
 ...
 'L 8730 CP', 'L 1916 BP', 'L 1651 EP', 'L 1070 CP', 'L 1831 CP', 'L 8468 CP',
 'L 0002 AP', 'L 1107 CP', 'L 0001 AP', 'L 1108 CP']
Length: 759, dtype: str

In [12]:
# Mengelompokkan berdasarkan Nopol dan menghitung jumlah Type unik
nopol_cek = df_final.groupby('Nopol')['Type'].nunique()

# Memfilter Nopol yang memiliki lebih dari 1 Type
nopol_berbeda = nopol_cek[nopol_cek > 1].reset_index()

print("Daftar Nopol yang memiliki lebih dari satu Type:")
print(nopol_berbeda)

Daftar Nopol yang memiliki lebih dari satu Type:
         Nopol  Type
0    L 0009 AP     2
1    L 0016 AP     2
2    L 0020 AP     2
3    L 0022 AP     2
4    L 0028 AP     2
..         ...   ...
262  L 9464 AP     2
263  L 9751 AP     2
264  L 9805 CP     3
265  L 9806 CP     3
266  L 9808 CP     2

[267 rows x 2 columns]

In [13]:
# Mendapatkan list Nopol yang bermasalah
list_nopol = df_final.groupby('Nopol')['Type'].nunique()
list_nopol = list_nopol[list_nopol > 1].index

# Menampilkan baris yang memiliki Nopol tersebut (hanya kolom Nopol dan Type)
detail_perbedaan = df_final[df_final['Nopol'].isin(list_nopol)][['Nopol', 'Type']].drop_duplicates().sort_values('Nopol')

print(detail_perbedaan)

          Nopol                       Type
167   L 0009 AP                        IMV
1422  L 0009 AP     KIJANG INNOVA 2.0 G AT
592   L 0016 AP                        IMV
965   L 0016 AP     KIJANG INNOVA 2.0 G AT
476   L 0020 AP                        IMV
...         ...                        ...
1641  L 9806 CP  TBR54F TURBO LM AMBULANCE
467   L 9806 CP                      TBR54
459   L 9806 CP                     TBR541
468   L 9808 CP                      TBR54
1143  L 9808 CP  TBR54F TURBO LM AMBULANCE

[600 rows x 2 columns]

In [ ]:
import pandas as pd

# 1. Load data
df = pd.read_csv('Data_Kendaraan_Bersih.csv', sep=';')

# 2. Standarisasi teks (Huruf besar & hapus spasi)
df['Type'] = df['Type'].astype(str).str.strip().str.upper()

def pilih_tipe_terbaik(group):
    # Hilangkan pilihan 'OTHER', 'OTHERS', atau 'OTHER D' dari pencarian sementara
    specific_types = group[~group.isin(['OTHER', 'OTHERS', 'OTHER D', 'NAN', 'UNKNOWN'])]
    
    if not specific_types.empty:
        # Jika ada tipe spesifik, ambil yang paling sering muncul di antara tipe spesifik itu
        return specific_types.value_counts().idxmax()
    else:
        # Jika memang semuanya 'OTHER', barulah ambil 'OTHER'
        return group.value_counts().idxmax()

# 3. Buat referensi Nopol ke Type dengan logika "Anti-Other"
nopol_type_ref = df.groupby('Nopol')['Type'].apply(pilih_tipe_terbaik).reset_index()

# 4. Gabungkan kembali ke dataframe utama
df_final_clean = df.drop(columns=['Type']).merge(nopol_type_ref, on='Nopol', how='left')

# 5. Susun kolom dan simpan
cols = ['Nopol', 'Bulan', 'Vendor', 'Type', 'Total Biaya', 'Keterangan', 'Tahun', 'Sumber']
df_final_clean = df_final_clean[cols]

df_final_clean.to_csv('dataBener.csv', index=False, sep=';')

print("Pembersihan selesai! Nopol dengan tipe campuran kini menggunakan tipe yang lebih spesifik.")

Pembersihan selesai! Nopol dengan tipe campuran kini menggunakan tipe yang lebih spesifik.

In [19]:
import pandas as pd

# 1. Load Data
df = pd.read_csv('dataBener.csv', sep=';')

# 2. Standarisasi Teks (Agar pencarian lebih akurat)
df['Type'] = df['Type'].astype(str).str.upper()
df['Vendor_Original'] = df['Vendor'] # Simpan nama asli buat cadangan

# 3. Fungsi Mapping Vendor berdasarkan Type
def ganti_vendor_by_type(row):
    v_type = row['Type']
    
    # Logika Mapping: Jika Type mengandung kata tertentu, arahkan ke Vendor Utama
    if any(x in v_type for x in ['INNOVA', 'HIACE', 'CAMRY', 'FORTUNER', 'KIJANG']):
        return 'TOYOTA SERVICE CENTER (ASTRA)'
    
    elif any(x in v_type for x in ['PANTHER', 'ISUZU', 'NMR', 'NKR']):
        return 'ISUZU SERVICE CENTER (ASTRA)'
    
    elif any(x in v_type for x in ['APV', 'SUZUKI']):
        return 'SUZUKI SERVICE CENTER (UMC)'
    
    elif 'HINO' in v_type:
        return 'HINO SERVICE CENTER (DUTA CEMERLANG)'
    
    elif 'MITSUBISHI' in v_type:
        return 'MITSUBISHI SERVICE CENTER'
    
    # Jika tidak ada yang cocok, gunakan Vendor asli yang sudah dibersihkan
    return row['Vendor']

# 4. Eksekusi Perubahan
df['Vendor'] = df.apply(ganti_vendor_by_type, axis=1)

# 5. Simpan ke File Baru
df.to_csv('Data_Pemeliharaan_Vendor_Mapped.csv', index=False, sep=';')

print("Berhasil! Vendor sekarang dikelompokkan berdasarkan Type kendaraan.")
print(df[['Type', 'Vendor']].drop_duplicates().head(10))

Berhasil! Vendor sekarang dikelompokkan berdasarkan Type kendaraan.
                            Type  \
0                  KIJANG INNOVA
1                          CAMRY
3                            IMV
6         KIJANG INNOVA 2.0 G AT
8     MITSUBISHIPAJERO SPORT 2.5
9           KIJANG INNOVA G XW42
10                        SOLUNA
11  COMMUTER ACE MANUAL VIN 2019
12                         HIACE
14                        KIJANG

                                               Vendor
0                       TOYOTA SERVICE CENTER (ASTRA)
1                       TOYOTA SERVICE CENTER (ASTRA)
3   PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI ...
6                       TOYOTA SERVICE CENTER (ASTRA)
8                           MITSUBISHI SERVICE CENTER
9                       TOYOTA SERVICE CENTER (ASTRA)
10  PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI ...
11  PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI ...
12                      TOYOTA SERVICE CENTER (ASTRA)
14                      TOYOTA SERVICE CENTER (ASTRA)

In [20]:
import pandas as pd

# 1. Load Data
df = pd.read_csv('Data_Pemeliharaan_Vendor_Mapped.csv', sep=';')

# 2. Fungsi untuk mengelompokkan Keterangan
def kategori_kerusakan(text):
    text = str(text).upper()
    
    if 'BERAT' in text:
        return 'RUSAK BERAT'
    elif 'SEDANG' in text:
        return 'RUSAK SEDANG'
    elif 'RINGAN' in text:
        return 'RUSAK RINGAN'
    elif 'TUNE UP' in text or 'BERKALA' in text:
        return 'TUNE UP'
    else:
        # Jika tidak mengandung kata kunci di atas, tetap gunakan teks asli atau 'LAINNYA'
        return 'TUNE UP' # Biasanya perawatan rutin masuk ke Tune Up

# 3. Eksekusi Perbaikan
df['Keterangan'] = df['Keterangan'].apply(kategori_kerusakan)

# 4. Simpan ke CSV Final
df.to_csv('Data_Pemeliharaan_Vendor_Mapped.csv', index=False, sep=';')

print("Kolom Keterangan berhasil disederhanakan!")
print(df['Keterangan'].value_counts())

Kolom Keterangan berhasil disederhanakan!
Keterangan
TUNE UP         1238
RUSAK SEDANG     918
RUSAK RINGAN     904
RUSAK BERAT      177
Name: count, dtype: int64

In [4]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Load Data
df = pd.read_csv('dataBener.csv', sep=';')

# Fungsi Preprocessing (Pembersihan Awal)
def preprocess_text(text):
    if pd.isna(text): return ""
    text = str(text).lower()
    # Hapus kata-kata badan usaha yang tidak unik
    stopwords = ['pt.', 'pt ', 'cv.', 'cv ', 'ud.', 'ud ', 'tbk.', 'tbk', '(', ')', '-']
    for word in stopwords:
        text = text.replace(word, ' ')
    text = re.sub(r'[^\w\s]', ' ', text) # Hapus sisa tanda baca
    text = re.sub(r'\s+', ' ', text).strip() # Hapus spasi ganda
    return text

# Siapkan data unik untuk dianalisa
vendor_counts = df['Vendor'].value_counts()
unique_vendors = vendor_counts.index.tolist()
cleaned_vendors = [preprocess_text(v) for v in unique_vendors]

# 2. Vektorisasi dengan TF-IDF & N-Grams
# ngram_range=(3,3) berarti kita memecah teks per 3 huruf untuk mendeteksi kemiripan ejaan
vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(3, 3))
tfidf_matrix = vectorizer.fit_transform(cleaned_vendors)

# 3. Hitung Kemiripan (Cosine Similarity)
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# 4. Clustering (Pengelompokan Otomatis)
group_map = {} 
visited = set()
threshold = 0.55 # Ambang batas kemiripan (bisa diatur, 0.55 cukup moderat)

for i, vendor_i in enumerate(unique_vendors):
    if vendor_i in visited: continue
    
    # Vendor ini menjadi "Ketua Grup"
    group_label = vendor_i 
    group_map[vendor_i] = group_label
    visited.add(vendor_i)
    
    # Cari vendor lain yang mirip dengan Ketua Grup ini
    for j, vendor_j in enumerate(unique_vendors):
        if vendor_j in visited: continue
            
        similarity = cosine_sim[i, j]
        
        # Jika kemiripan di atas threshold, masukkan ke grup ini
        if similarity > threshold:
            group_map[vendor_j] = group_label
            visited.add(vendor_j)

# Terapkan hasil grouping ke DataFrame
df['Vendor_TextMining'] = df['Vendor'].map(group_map)

# Simpan dan Tampilkan Contoh Hasil
print("Contoh Hasil Pengelompokan Text Mining:")
print(df[['Vendor', 'Vendor_TextMining']].drop_duplicates().head(10))

df.to_csv('dataBener_TextMining.csv', index=False, sep=';')

Contoh Hasil Pengelompokan Text Mining:
                                                Vendor  \
0    PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI ...
8                    PT. SRIKANDI DIAMOND INDAH MOTORS
73   PT. ASTRA INTERNATIONAL ISUZU CABANG KOMBES DU...
99    PT. ASTRA INTERNATIONAL ISUZU CABANG HR MUHAMMAD
220                          PT.  UNITED MOTORS CENTRE
247                                    CV. Damar karya
250                                        UD. Jaya AC
260  PT. ASTRA INTERNATIONAL TOYOTA CABANG BASUKI R...
267                         PT. INDO SUNMOTOR GEMILANG
282          PT. ASTRA INTERNATIONAL ISUZU CABANG WARU

                                     Vendor_TextMining
0    PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI ...
8                     PT SRIKANDI DIAMOND INDAH MOTORS
73   PT. ASTRA INTERNATIONAL TBK (ISUZU KOMBES M DU...
99   PT. ASTRA INTERNATIONAL - TBK  ISUZU CABANG HR...
220                   PT UNITED MOTORS CENTER (SUZUKI)
247                                    CV. DAMAR KARYA
250                                  CV. Jaya AC Denso
260  PT. ASTRA INTERNATIONAL TBK (AUTO2000 BASUKI R...
267                         PT. INDO SUNMOTOR GEMILANG
282           PT. ASTRA INTERNATIONAL TBK (ISUZU WARU)

In [ ]:
list_vendor = df['Vendor_TextMining'].dropna().unique()

# 3. Menampilkan daftar nama vendor (diurutkan abjad agar mudah dibaca)
print("Daftar Variasi Nama Vendor:")
for nama in sorted(list_vendor):
    print(nama)

# 4. Jika ingin melihat jumlah data per masing-masing nama vendor
print("\nJumlah Data per Nama Vendor:")
print(df['Vendor_TextMining'].value_counts())

Daftar Variasi Nama Vendor:
CV. ASRI
CV. ASRI JENGGOLO (TOYOTA)
CV. ASRI PUCANG (TOYOTA)
CV. DAMAR KARYA
CV. Jaya AC Denso
CV. Sumber Agung Variasi
PT SRIKANDI DIAMOND INDAH MOTORS
PT UNITED MOTORS CENTER (SUZUKI)
PT. ASTRA INTERNATIONAL - TBK  ISUZU CABANG HR Muhammad
PT. ASTRA INTERNATIONAL TBK (AUTO2000 BASUKI RACHMAT)
PT. ASTRA INTERNATIONAL TBK (ISUZU KOMBES M DURYAT)
PT. ASTRA INTERNATIONAL TBK (ISUZU MARGOMULYO)
PT. ASTRA INTERNATIONAL TBK (ISUZU WARU)
PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI RAHMAT
PT. INDO SUNMOTOR GEMILANG
PT. MURNI BERLIAN MOTORS
UD. BERKAT JAYA ABADI

Jumlah Data per Nama Vendor:
Vendor_TextMining
PT. ASTRA INTERNATIONAL TBK (ISUZU KOMBES M DURYAT)        1072
PT. ASTRA INTERNATIONAL TBK (AUTO2000 BASUKI RACHMAT)       618
PT. ASTRA INTERNATIONAL TBK (ISUZU WARU)                    569
PT. ASTRA INTERNATIONAL TBK (ISUZU MARGOMULYO)              255
PT. ASTRA INTERNATIONAL - TBK  ISUZU CABANG HR Muhammad     178
PT. ASTRA INTERNATIONAL TOYOTA CABANG  BASUKI RAHMAT        176
PT UNITED MOTORS CENTER (SUZUKI)                            104
CV. ASRI PUCANG (TOYOTA)                                     75
CV. ASRI                                                     62
PT SRIKANDI DIAMOND INDAH MOTORS                             53
CV. Jaya AC Denso                                            40
CV. DAMAR KARYA                                              14
PT. MURNI BERLIAN MOTORS                                     12
UD. BERKAT JAYA ABADI                                         5
PT. INDO SUNMOTOR GEMILANG                                    2
CV. Sumber Agung Variasi                                      1
CV. ASRI JENGGOLO (TOYOTA)                                    1
Name: count, dtype: int64